FROM openjdk:8
ENV AWS_ACCESS_KEY_ID=AKIATROY27SOEUM2THKJ \
    AWS_SECRET_KEY=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
ADD target/SpringAWSProject-1.0.jar app.jar
EXPOSE 80
ENTRYPOINT ["java","-jar","app.jar"]