FROM openjdk:8
ENV AWS_ACCESS_KEY_ID=AKIAUKUS5RYZESNDS3XO \
    AWS_SECRET_KEY=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
ADD target/SpringAWSProject-1.0.jar app.jar
EXPOSE 80
ENTRYPOINT ["java","-jar","app.jar"]