FROM openjdk:8
ENV AWS_ACCESS_KEY_ID=AKIAZNRI5PY73L34VJXQ \
    AWS_SECRET_KEY=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
ADD target/SpringAWSProject-1.0.jar app.jar
EXPOSE 80
ENTRYPOINT ["java","-jar","app.jar"]