amazon:
  access:
    key: AKIAQHJLPQ37MM62FG7R
    secret-key: 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
  region: us-east-1
  end-point:
    url: dynamodb.us-east-1.amazonaws.com
  kms:
    keyarn: arn:aws:kms:us-east-1:015660451582:key/7aa4adc8-d29e-40ba-8645-58a381d22558