amazon:
  access:
    key: AKIAQVBGJMYARKOE2XEX
    secret-key: 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
  region: us-east-1
  end-point:
    url: dynamodb.us-east-1.amazonaws.com
  kms:
    keyarn: arn:aws:kms:us-east-1:598830968647:key/37c694a0-beb9-47c0-8f43-56234c1997d0